/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h43WxHYwGcNqk1ddSabSmh

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsip6Lkoc6YmH } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Ip6lkoc6YmH_/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsip6Lkoc6YmH
});
